on: push
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy (Static Website)
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Upload via SFTP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ftp-quaiantiquerestaurantfg.alwaysdata.net
        username: quaiantiquerestaurantfg
        key: ${{ secrets.ssh_key }}
        port: 22

        # Tout le site statique
        source: "./"

        # Dossier AlwaysData
        target: "/home/quaiantiquerestaurantfg/www"

        # Exclusions simples
        exclude: |
          **/.git*
          **/node_modules/**
          **/.DS_Store
