on: push
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🔧 Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22.22.3'

    - name: 📦 Install dependencies
      run: npm install

    - name: 📂 Upload via SFTP (version simple)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ssh-quaiantiquerestaurantfg.alwaysdata.net
        username: quaiantiquerestaurantfg
        password: ${{ secrets.ftp_password }}
        port: 22
        script: |
          sftp -o StrictHostKeyChecking=no -P 22 quaiantiquerestaurantfg@ssh-quaiantiquerestaurantfg.alwaysdata.net <<EOF
          put -r * /home/quaiantiquerestaurantfg/www
          EOF
